/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cinema.gui;

/**
 *
 * @author barbo
 */
public class AcceuilAdmin extends javax.swing.JFrame {

    /**
     * Creates new form AcceuilAdmin
     */
    public AcceuilAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bouttonFilms = new javax.swing.JButton();
        bouttonClients = new javax.swing.JButton();
        bouttonSalles = new javax.swing.JButton();
        bouttonSeances = new javax.swing.JButton();
        bouttonReservations = new javax.swing.JButton();
        bouttonRetour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenue , Administrateur ! ");

        bouttonFilms.setText("Conculter les Films");
        bouttonFilms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouttonFilmsActionPerformed(evt);
            }
        });

        bouttonClients.setText("Conculter les Clients");
        bouttonClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouttonClientsActionPerformed(evt);
            }
        });

        bouttonSalles.setText("Conculter les Salles");
        bouttonSalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouttonSallesActionPerformed(evt);
            }
        });

        bouttonSeances.setText("Conculter les Seances");
        bouttonSeances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouttonSeancesActionPerformed(evt);
            }
        });

        bouttonReservations.setText("Conculter les Reservations");
        bouttonReservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouttonReservationsActionPerformed(evt);
            }
        });

        bouttonRetour.setText("Retour ");
        bouttonRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouttonRetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel1)
                .addContainerGap(138, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bouttonFilms, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bouttonClients, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bouttonReservations, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bouttonSeances, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bouttonSalles, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bouttonRetour)
                .addGap(191, 191, 191))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(bouttonFilms)
                .addGap(33, 33, 33)
                .addComponent(bouttonClients)
                .addGap(29, 29, 29)
                .addComponent(bouttonSalles)
                .addGap(28, 28, 28)
                .addComponent(bouttonSeances)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(bouttonReservations)
                .addGap(32, 32, 32)
                .addComponent(bouttonRetour)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bouttonFilmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouttonFilmsActionPerformed
        // TODO add your handling code here:
        bouttonFilms.addActionListener(e -> {
    new GestionFilmsFrame().setVisible(true);
});

    }//GEN-LAST:event_bouttonFilmsActionPerformed

    private void bouttonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouttonRetourActionPerformed
        // TODO add your handling code here:
        bouttonRetour.addActionListener(e -> {
            new MainFrame().setVisible(true); // Remplace si ta classe a un nom différent
            dispose(); // Fermer la fenêtre actuelle
        });
    }//GEN-LAST:event_bouttonRetourActionPerformed

    private void bouttonClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouttonClientsActionPerformed
        // TODO add your handling code here:
        bouttonClients.addActionListener(e -> {
    new GestionClientsFrame().setVisible(true);
    dispose();
});

    }//GEN-LAST:event_bouttonClientsActionPerformed

    private void bouttonSallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouttonSallesActionPerformed
        // TODO add your handling code here:
        bouttonSalles.addActionListener(e -> {
    new GestionSallesFrame().setVisible(true);
    dispose();
});

    }//GEN-LAST:event_bouttonSallesActionPerformed

    private void bouttonSeancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouttonSeancesActionPerformed
        // TODO add your handling code here:
        bouttonSeances.addActionListener(e -> {
    new GestionSeancesFrame().setVisible(true);
    dispose();});
    }//GEN-LAST:event_bouttonSeancesActionPerformed

    private void bouttonReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouttonReservationsActionPerformed
        // TODO add your handling code here:
        bouttonReservations.addActionListener(e -> {
    new GestionReservationsFrame().setVisible(true);
    dispose();
});

    }//GEN-LAST:event_bouttonReservationsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcceuilAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcceuilAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcceuilAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcceuilAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcceuilAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouttonClients;
    private javax.swing.JButton bouttonFilms;
    private javax.swing.JButton bouttonReservations;
    private javax.swing.JButton bouttonRetour;
    private javax.swing.JButton bouttonSalles;
    private javax.swing.JButton bouttonSeances;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
